_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: posts
    glob: []
    name: Posts
    icon: event_available
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    html: true
