_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  home:
    path: ''
    name: home
    icon: wysiwyg
    disable_url: false
    description: pages for "home" section
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  parents:
    path: parents
    glob:
    name: parents
    singular_name:
    icon: person
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: pages for "parents" section
    preview:
    sort:
      key:
      order:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
      section_1:
        label: "title"
        group: "section 1"
      caption_1:
        label: "caption"
        group: "section 1"
    _groups:
      "section 1":
        label: "section 1"
        collapsed: true
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  tournaments:
    path: tournaments
    glob:
    name: tournaments
    singular_name:
    icon: trophy
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: pages for "tournaments" section
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  calendar:
    path: calendar
    glob:
    name: calendar
    singular_name:
    icon: calendar_month
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: pages for "calendar" section
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  resources:
    path: resources
    glob:
    name: resources
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: pages for "resources" section
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  newport:
    path: newport
    glob:
    name: newport s&d
    singular_name:
    icon: school
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: pages for "nhs s&d" section
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_enabled_editors:
  - visual
  - content
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    html: true
build:
  command: npx @11ty/eleventy
  output: _site
