_schema: _schema
source: /src/
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: posts
    glob: []
    name: Posts
    icon: event_available
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - visual
  - content
timezone: America/Los_Angeles
markdown:
  engine: commonmark
  options:
    html: true
build:
  command: npx @11ty/eleventy
  output: _site
